import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ClerkProvider
} from '@clerk/nextjs'
import "./globals.css";

import { ThemeProvider } from "@/app/providers";
import Appbar from "@/components/Appbar";
import Footer from "@/components/Footer";
//const NoSSR_APPBar = dynamic(() => import("@/components/Appbar"), { ssr: true })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <>
        <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider>
            <Appbar />
            
            {children}
            <Footer />
            </ThemeProvider>
          </body>
        </html>
        </>
      </ClerkProvider>
  );
}
